In [5]:
import json
import requests
import pandas as pd

In [2]:
response = requests.get('http://hp-api.herokuapp.com/api/characters')
#response
results = response.json()
#results

In [9]:
results[1]

{'name': 'Hermione Granger',
 'alternate_names': [''],
 'species': 'human',
 'gender': 'female',
 'house': 'Gryffindor',
 'dateOfBirth': '19-09-1979',
 'yearOfBirth': 1979,
 'wizard': True,
 'ancestry': 'muggleborn',
 'eyeColour': 'brown',
 'hairColour': 'brown',
 'wand': {'wood': 'vine', 'core': 'dragon heartstring', 'length': ''},
 'patronus': 'otter',
 'hogwartsStudent': True,
 'hogwartsStaff': False,
 'actor': 'Emma Watson',
 'alternate_actors': [''],
 'alive': True,
 'image': 'http://hp-api.herokuapp.com/images/hermione.jpeg'}

In [7]:
data = pd.DataFrame(results)
data.head()

,name,alternate_names,species,gender,house,dateOfBirth,yearOfBirth,wizard,ancestry,eyeColour,hairColour,wand,patronus,hogwartsStudent,hogwartsStaff,actor,alternate_actors,alive,image
0,Harry Potter,[],human,male,Gryffindor,31-07-1980,1980,True,half-blood,green,black,"{'wood': 'holly', 'core': 'phoenix feather', '...",stag,True,False,Daniel Radcliffe,[],True,http://hp-api.herokuapp.com/images/harry.jpg
1,Hermione Granger,[],human,female,Gryffindor,19-09-1979,1979,True,muggleborn,brown,brown,"{'wood': 'vine', 'core': 'dragon heartstring',...",otter,True,False,Emma Watson,[],True,http://hp-api.herokuapp.com/images/hermione.jpeg
2,Ron Weasley,[],human,male,Gryffindor,01-03-1980,1980,True,pure-blood,blue,red,"{'wood': 'willow', 'core': 'unicorn tail-hair'...",Jack Russell terrier,True,False,Rupert Grint,[],True,http://hp-api.herokuapp.com/images/ron.jpg
3,Draco Malfoy,[],human,male,Slytherin,05-06-1980,1980,True,pure-blood,grey,blonde,"{'wood': 'hawthorn', 'core': 'unicorn tail-hai...",,True,False,Tom Felton,[],True,http://hp-api.herokuapp.com/images/draco.jpg
4,Minerva McGonagall,[],human,female,Gryffindor,04-10-1925,1925,True,,,black,"{'wood': '', 'core': '', 'length': ''}",tabby cat,False,True,Dame Maggie Smith,[],True,http://hp-api.herokuapp.com/images/mcgonagall.jpg

In [8]:
flattened_data = pd.json_normalize(results)
flattened_data.head()

,name,alternate_names,species,gender,house,dateOfBirth,yearOfBirth,wizard,ancestry,eyeColour,...,patronus,hogwartsStudent,hogwartsStaff,actor,alternate_actors,alive,image,wand.wood,wand.core,wand.length
0,Harry Potter,[],human,male,Gryffindor,31-07-1980,1980,True,half-blood,green,...,stag,True,False,Daniel Radcliffe,[],True,http://hp-api.herokuapp.com/images/harry.jpg,holly,phoenix feather,11
1,Hermione Granger,[],human,female,Gryffindor,19-09-1979,1979,True,muggleborn,brown,...,otter,True,False,Emma Watson,[],True,http://hp-api.herokuapp.com/images/hermione.jpeg,vine,dragon heartstring,
2,Ron Weasley,[],human,male,Gryffindor,01-03-1980,1980,True,pure-blood,blue,...,Jack Russell terrier,True,False,Rupert Grint,[],True,http://hp-api.herokuapp.com/images/ron.jpg,willow,unicorn tail-hair,14
3,Draco Malfoy,[],human,male,Slytherin,05-06-1980,1980,True,pure-blood,grey,...,,True,False,Tom Felton,[],True,http://hp-api.herokuapp.com/images/draco.jpg,hawthorn,unicorn tail-hair,10
4,Minerva McGonagall,[],human,female,Gryffindor,04-10-1925,1925,True,,,...,tabby cat,False,True,Dame Maggie Smith,[],True,http://hp-api.herokuapp.com/images/mcgonagall.jpg,,,

## SECOND API

In [10]:
response = requests.get('https://nova.bitcambio.com.br/api/v3/public/getassets')
#response
results = response.json()

In [12]:
data = pd.DataFrame(results)
data.head()

   success message                                             result
0     True          {'Asset': 'AXS', 'AssetLong': 'Axie Infinity S...
1     True          {'Asset': 'BTC', 'AssetLong': 'Bitcoin', 'MinC...
2     True          {'Asset': 'DOGE', 'AssetLong': 'Dogecoin', 'Mi...
3     True          {'Asset': 'ETH', 'AssetLong': 'Ethereum', 'Min...
4     True          {'Asset': 'LTC', 'AssetLong': 'Litecoin', 'Min...

In [13]:
flattened_data = pd.json_normalize(results)
flattened_data.head()

   success message                                             result
0     True          [{'Asset': 'AXS', 'AssetLong': 'Axie Infinity ...

## THIRD API

In [19]:
response = requests.get('https://blockchain.info/blocks/1573858800000?format=json')
results = response.json()

In [20]:
results

[{'hash': '0000000000000000000efcea1cc1a169955e9cf6f039ddeabfdd1da1ac6d9899',
  'height': 603966,
  'time': 1573858343,
  'block_index': 603966},
 {'hash': '0000000000000000000ee40dc80e8ddd28d6389ba8dd59bb147b48d8f7a87f13',
  'height': 603965,
  'time': 1573857408,
  'block_index': 603965},
 {'hash': '0000000000000000000cc742f3903cf8960ffd9c51ad17d03182bf471c59f002',
  'height': 603964,
  'time': 1573856957,
  'block_index': 603964},
 {'hash': '00000000000000000004f941b4a37d7500a1c90a681ed0df9eacf845f0c40e3e',
  'height': 603963,
  'time': 1573856530,
  'block_index': 603963},
 {'hash': '000000000000000000072200d4179a900d6b4ab78cd0add270a727afbf3a17f7',
  'height': 603962,
  'time': 1573856123,
  'block_index': 603962},
 {'hash': '0000000000000000000915ef354f0e6dc2d47c0a46b232225d8a3eacf33ed5ad',
  'height': 603961,
  'time': 1573855600,
  'block_index': 603961},
 {'hash': '000000000000000000080ed5e21f02e05d0773c3d501f1c1525f7dfcba2ee980',
  'height': 603960,
  'time': 1573854485,
  'block_index': 603960},
 {'hash': '000000000000000000076155ad40708c50b8558b6a0fe9cb4a718dbc7fed3a01',
  'height': 603959,
  'time': 1573853926,
  'block_index': 603959},
 {'hash': '00000000000000000011ce9d6ba5d575877acb4da3f4bbfde0bd6500c24a5539',
  'height': 603958,
  'time': 1573852615,
  'block_index': 603958},
 {'hash': '0000000000000000001375d406bab0832a7a7299bc72c5c5a0bf5ad4f55dc47f',
  'height': 603957,
  'time': 1573852494,
  'block_index': 603957},
 {'hash': '00000000000000000004b5d28c14804d5baa1c8e4516dcaaef5452ed7c031802',
  'height': 603956,
  'time': 1573851492,
  'block_index': 603956},
 {'hash': '000000000000000000040b8cc03a5948ef5cbe5f6f3e05c252fe7408ebddccf7',
  'height': 603955,
  'time': 1573851447,
  'block_index': 603955},
 {'hash': '0000000000000000001500a41bba6dbb467c56df3e46c10870df77ca801f3f5a',
  'height': 603954,
  'time': 1573851033,
  'block_index': 603954},
 {'hash': '00000000000000000000dd3699b2ead386675feaee6fc2917d0832d2df5b9562',
  'height': 603953,
  'time': 1573850667,
  'block_index': 603953},
 {'hash': '00000000000000000008d159189ab186342e7dad38d6a95ac7a41f829ab4607c',
  'height': 603952,
  'time': 1573850277,
  'block_index': 603952},
 {'hash': '0000000000000000000766dec927fad9efd4aceff58e467c43b05d2eea3178ac',
  'height': 603951,
  'time': 1573848546,
  'block_index': 603951},
 {'hash': '00000000000000000003fca034bd9be6f71ee85177d1b113abc2a21b8daecb5a',
  'height': 603950,
  'time': 1573847115,
  'block_index': 603950},
 {'hash': '0000000000000000000ef02b50ef383acd482b5df0962d59c9e66d483eeba7ef',
  'height': 603949,
  'time': 1573846648,
  'block_index': 603949},
 {'hash': '0000000000000000000605a6e8d38d1f32e1deb677b4ed212efae317ae11a045',
  'height': 603948,
  'time': 1573846125,
  'block_index': 603948},
 {'hash': '000000000000000000052ee52d56f9e382f80240460d81051634ac938b42f562',
  'height': 603947,
  'time': 1573845749,
  'block_index': 603947},
 {'hash': '00000000000000000015abbc8b54e1632ced2240b22ced1fca006b2e9060aa0a',
  'height': 603946,
  'time': 1573844624,
  'block_index': 603946},
 {'hash': '0000000000000000000cd0566195a0fd624dbc0622586a7f6c4e264aa0bee5f1',
  'height': 603945,
  'time': 1573844412,
  'block_index': 603945},
 {'hash': '000000000000000000145600de98dc423ae2df3449b1370e184db0c7cdacb724',
  'height': 603944,
  'time': 1573841959,
  'block_index': 603944},
 {'hash': '000000000000000000132c3e8389df0e998cdeaa23950c60a307e6e0f43258ec',
  'height': 603943,
  'time': 1573840606,
  'block_index': 603943},
 {'hash': '0000000000000000000ba5fca01b304d3becceb08945a2c97eeef1f657b3f416',
  'height': 603942,
  'time': 1573840280,
  'block_index': 603942},
 {'hash': '0000000000000000000180e090cb1195f6b97c42c01f455f1d0e996ad5d3dbb3',
  'height': 603941,
  'time': 1573838633,
  'block_index': 603941},
 {'hash': '0000000000000000000037483b8bf567891c98d9811bf583e8e158c562c34be3',
  'height': 603940,
  'time': 1573837967,
  'block_index': 603940},
 {'hash': '000000000000000000004b07396e26a58052695cffaf54e1446908181f7c1c36',
  'height': 603939,
  'time': 1573837680,
  'block_index': 603939},
 {'hash': '000000000000000000057a3c3a621a88486514fef6f0cd55ddbb57b72f27fa5e',
  'height': 603938,
  'time': 1573837621,
  'block_index': 603938},
 {'hash': '0000000000000000000e1b6366a7a8b8fcffb0236ecdefa73f9d7e8918ea891a',
  'height': 603937,
  'time': 1573836938,
  'block_index': 603937},
 {'hash': '000000000000000000000e1876d4b54b1650c53b2ce3273dfed34f3f8ad04993',
  'height': 603936,
  'time': 1573835993,
  'block_index': 603936},
 {'hash': '0000000000000000001283e43fcaf3e32ec213bc752fc336cbc06e46e0d387bb',
  'height': 603935,
  'time': 1573835963,
  'block_index': 603935},
 {'hash': '00000000000000000001291d94dc1973fdfc9c80e496e714f735899294c8bd62',
  'height': 603934,
  'time': 1573835879,
  'block_index': 603934},
 {'hash': '00000000000000000008f332c7a977dba2322d69f952709c374d9726ad45b171',
  'height': 603933,
  'time': 1573835735,
  'block_index': 603933},
 {'hash': '0000000000000000000743308059c85d37f1fb55b75e7035db0366998ef8b64a',
  'height': 603932,
  'time': 1573834355,
  'block_index': 603932},
 {'hash': '00000000000000000011cbb903be43391cc97d799324aa0d9d68c8f5aa87c75a',
  'height': 603931,
  'time': 1573834237,
  'block_index': 603931},
 {'hash': '0000000000000000000392428b70520bfb044c7f1de00453e93d61916cfaf9d3',
  'height': 603930,
  'time': 1573834082,
  'block_index': 603930},
 {'hash': '00000000000000000015d44b15fe74a23b6f40aea80e7208f93cee8036d3fc52',
  'height': 603929,
  'time': 1573834006,
  'block_index': 603929},
 {'hash': '0000000000000000000fea5ca9265952b67832a20920baf5511a5de1b178340e',
  'height': 603928,
  'time': 1573833877,
  'block_index': 603928},
 {'hash': '0000000000000000000bfe6ecce4b3073fd88f7e837a01ba4c169e9b7a705122',
  'height': 603927,
  'time': 1573833193,
  'block_index': 603927},
 {'hash': '0000000000000000000e00ec920ffa0481632488cd40b8c724005b60c484172d',
  'height': 603926,
  'time': 1573832662,
  'block_index': 603926},
 {'hash': '00000000000000000004b31b4f509518f557eced194561df32f68a04d052bae5',
  'height': 603925,
  'time': 1573832167,
  'block_index': 603925},
 {'hash': '00000000000000000008c9744975a2bb46bd4840e0298f4607fd713413a86b11',
  'height': 603924,
  'time': 1573831983,
  'block_index': 603924},
 {'hash': '00000000000000000001238ccbdc4013aada96390840cdb2f466cae4a0bb8cfe',
  'height': 603923,
  'time': 1573831315,
  'block_index': 603923},
 {'hash': '00000000000000000002efd35064b700661e4ea0cdebf853b03a89b0fa894a1c',
  'height': 603922,
  'time': 1573831166,
  'block_index': 603922},
 {'hash': '0000000000000000000595a6d0e56089d781d0cdb8e5376db21f75b19d726064',
  'height': 603921,
  'time': 1573831026,
  'block_index': 603921},
 {'hash': '0000000000000000000db6dd43f16dd7388e04978d6e0c9fe09bee5f19230321',
  'height': 603920,
  'time': 1573830370,
  'block_index': 603920},
 {'hash': '0000000000000000000f9be1aaed102a5a97fa35174a228cd41b705525005a0e',
  'height': 603919,
  'time': 1573830208,
  'block_index': 603919},
 {'hash': '000000000000000000102f6dff6b04df7a9c38cb6d8a427c902a7ee18b29e7db',
  'height': 603918,
  'time': 1573829984,
  'block_index': 603918},
 {'hash': '0000000000000000001041c9e6a632d50f5d099bd2b4057fd97f23d0e13e9fdf',
  'height': 603917,
  'time': 1573828988,
  'block_index': 603917},
 {'hash': '00000000000000000015436f8d17f371cb3d2bf7a5acfac227aeece258fdcc58',
  'height': 603916,
  'time': 1573828502,
  'block_index': 603916},
 {'hash': '0000000000000000000849b6109fa6814d2fb390b29314ebceef8cbc5edd97bc',
  'height': 603915,
  'time': 1573828136,
  'block_index': 603915},
 {'hash': '000000000000000000113205e55aff265f2bcd0dd4e8c127d10973e502586ba6',
  'height': 603914,
  'time': 1573826128,
  'block_index': 603914},
 {'hash': '00000000000000000005fec59e974cd91dd9dbc85e5781bea37c21e10f40bdb3',
  'height': 603913,
  'time': 1573825787,
  'block_index': 603913},
 {'hash': '0000000000000000000348717c790a75edb90692285400916724d75404f6c90b',
  'height': 603912,
  'time': 1573825769,
  'block_index': 603912},
 {'hash': '000000000000000000087574fc753d53755a780821dd7b6817b96a8132940f7e',
  'height': 603911,
  'time': 1573824891,
  'block_index': 603911},
 {'hash': '0000000000000000000830ce2a4a5577d43b72214f69edfc70cb7388e0f901ae',
  'height': 603910,
  'time': 1573824553,
  'block_index': 603910},
 {'hash': '0000000000000000000556c228763901b5dffc27b19235f040edc18ef7c112ae',
  'height': 603909,
  'time': 1573824188,
  'block_index': 603909},
 {'hash': '000000000000000000067aa5e9eb2701676653095cb9d8b6b198d0db1a4b15c9',
  'height': 603908,
  'time': 1573823961,
  'block_index': 603908},
 {'hash': '00000000000000000010b7cf7dbab793c19fb90d82a7f6daa57f8c98e247dc52',
  'height': 603907,
  'time': 1573823494,
  'block_index': 603907},
 {'hash': '000000000000000000033fd2fbf01f9d2deba3e7dc0aec38ca111dcfc331c591',
  'height': 603906,
  'time': 1573822451,
  'block_index': 603906},
 {'hash': '0000000000000000000a193358f52bc26a0d19b8385377909eb4b9b4fc762b27',
  'height': 603905,
  'time': 1573821492,
  'block_index': 603905},
 {'hash': '0000000000000000000a5a7fcf59a393194f37308cac2b13a3b76460209930f1',
  'height': 603904,
  'time': 1573820283,
  'block_index': 603904},
 {'hash': '0000000000000000000af18b0eedbcd0b61ce4a230099c47730bbc3d9ba6e9f2',
  'height': 603903,
  'time': 1573819874,
  'block_index': 603903},
 {'hash': '0000000000000000001017eaa038dc1d742e978bc29f6eefa26c5ff293dc0a3c',
  'height': 603902,
  'time': 1573818273,
  'block_index': 603902},
 {'hash': '00000000000000000010ef37d8d2450f1720920c5f2ed5ee30fe0d2a346decc8',
  'height': 603901,
  'time': 1573816594,
  'block_index': 603901},
 {'hash': '0000000000000000000d6ef6d5bc1394a873ff2af638dee50d3882d9c8827881',
  'height': 603900,
  'time': 1573815325,
  'block_index': 603900},
 {'hash': '0000000000000000001085347d507168ee91796318baa3b8aaa46451cc753a58',
  'height': 603899,
  'time': 1573814954,
  'block_index': 603899},
 {'hash': '000000000000000000097a7b5d1f68232116f3312e6383cb17162c0629722363',
  'height': 603898,
  'time': 1573814735,
  'block_index': 603898},
 {'hash': '000000000000000000118d2720b99d8879c7ca4c3ffd7c8129365c5004e03368',
  'height': 603897,
  'time': 1573814306,
  'block_index': 603897},
 {'hash': '000000000000000000153e0fcaf6bcfccd8f2a2e8f7ace7ca71951be0131aa52',
  'height': 603896,
  'time': 1573814072,
  'block_index': 603896},
 {'hash': '0000000000000000000434de6aa6409781b831eca000fe69594809a498ca13a7',
  'height': 603895,
  'time': 1573813594,
  'block_index': 603895},
 {'hash': '000000000000000000098bb3effed8edf77f0501eeaee95ad0b2fad38046ca7a',
  'height': 603894,
  'time': 1573813416,
  'block_index': 603894},
 {'hash': '00000000000000000007dcaa17bf6b745b0bdca77b6ac3337f38c40edc96e7ba',
  'height': 603893,
  'time': 1573812618,
  'block_index': 603893},
 {'hash': '0000000000000000000dd326fca34507d4131f3734919ca7145424812e8a032e',
  'height': 603892,
  'time': 1573812119,
  'block_index': 603892},
 {'hash': '0000000000000000000d3be0c224c0bd5e99f47e6de7fccd8c002ac0e569e5bc',
  'height': 603891,
  'time': 1573811810,
  'block_index': 603891},
 {'hash': '00000000000000000004ca9be9eeae50dbe6bac77016900ef9c68e4f70c37324',
  'height': 603890,
  'time': 1573810934,
  'block_index': 603890},
 {'hash': '0000000000000000000c6063e3e01fd898aae9f13791786f4f54c988fb782b82',
  'height': 603889,
  'time': 1573810759,
  'block_index': 603889},
 {'hash': '00000000000000000012ccab89036e3fdfe6d0debd882ec8c90943bf7e94a4f3',
  'height': 603888,
  'time': 1573810306,
  'block_index': 603888},
 {'hash': '0000000000000000000f339e0c5f20d6c16e4aebd6947fa72f28914389c353f0',
  'height': 603887,
  'time': 1573809483,
  'block_index': 603887},
 {'hash': '0000000000000000000492cf6ff55326bc1d0de603a0b1c7d3f6934c1370cb1f',
  'height': 603886,
  'time': 1573809429,
  'block_index': 603886},
 {'hash': '00000000000000000012e2f7c306bf7f5e4eadfc6eee82f22de9f0e97fa21008',
  'height': 603885,
  'time': 1573808017,
  'block_index': 603885},
 {'hash': '0000000000000000000b9ffe69a409d55f783b82d32e017cb18de19f725b7d80',
  'height': 603884,
  'time': 1573807372,
  'block_index': 603884},
 {'hash': '0000000000000000000d84546476002d09b40f83c7cce9cfc28da0cce1c9a3b8',
  'height': 603883,
  'time': 1573807237,
  'block_index': 603883},
 {'hash': '000000000000000000021a00080af86d9e79d5f8373f456ca6e2e3590044774b',
  'height': 603882,
  'time': 1573806881,
  'block_index': 603882},
 {'hash': '000000000000000000068791960201b779ed8b66325f4bc04a9098b55093d66d',
  'height': 603881,
  'time': 1573806431,
  'block_index': 603881},
 {'hash': '000000000000000000159382043214931630a2d7b70693768e72e1cae381e391',
  'height': 603880,
  'time': 1573806206,
  'block_index': 603880},
 {'hash': '0000000000000000001147761ca013f22444e37db4444424b6dbaa4632dab322',
  'height': 603879,
  'time': 1573805998,
  'block_index': 603879},
 {'hash': '0000000000000000000b154c3d3ce82307067d9a215629e58c45ac56398c61c5',
  'height': 603878,
  'time': 1573805727,
  'block_index': 603878},
 {'hash': '00000000000000000007acb310c17baedf8c8c8a3c9dda76fe1c8c31c5a04779',
  'height': 603877,
  'time': 1573802575,
  'block_index': 603877},
 {'hash': '000000000000000000077d6c393c3f62cacc0c423a20d138a78ac840cf138ac3',
  'height': 603876,
  'time': 1573802340,
  'block_index': 603876},
 {'hash': '0000000000000000000fdada0e552e588739ef163e57357fc8edb67b3ecdcfa9',
  'height': 603875,
  'time': 1573802205,
  'block_index': 603875},
 {'hash': '00000000000000000001349d0ab9a64481dac199b08ea54e4505b4658333cf2d',
  'height': 603874,
  'time': 1573802042,
  'block_index': 603874},
 {'hash': '00000000000000000012d71b099c1d81a259d071be6c4fa779f8f23a390f69b4',
  'height': 603873,
  'time': 1573801961,
  'block_index': 603873},
 {'hash': '00000000000000000003326a0288216a66c2c4dfaad7b545d1b93dd7566956ef',
  'height': 603872,
  'time': 1573801737,
  'block_index': 603872},
 {'hash': '0000000000000000001341fbdc90534d3d9112a96492b461ba708743ad135f9e',
  'height': 603871,
  'time': 1573801309,
  'block_index': 603871},
 {'hash': '0000000000000000001261c0960066324c189fc83df5080d161be0849a98a4a8',
  'height': 603870,
  'time': 1573801111,
  'block_index': 603870},
 {'hash': '00000000000000000011bd8c65e53cf01fbbccc0054cde901acb71db19d70721',
  'height': 603869,
  'time': 1573800670,
  'block_index': 603869},
 {'hash': '00000000000000000003d85ebafb86b82772aa4816aff03172d5d40691c127fc',
  'height': 603868,
  'time': 1573800374,
  'block_index': 603868},
 {'hash': '0000000000000000000b96dd782509be19a01a39a44b3481cfdb68e98beedb2b',
  'height': 603867,
  'time': 1573800000,
  'block_index': 603867},
 {'hash': '0000000000000000000de93825d2e26d019c32078b383d7375e2b4aca4613bbd',
  'height': 603866,
  'time': 1573798838,
  'block_index': 603866},
 {'hash': '0000000000000000000f04466f2da40e10cbab4ed5439a1b8e99786fb87138eb',
  'height': 603865,
  'time': 1573798063,
  'block_index': 603865},
 {'hash': '0000000000000000000f92ff5ad18b32e6b4ea332cd82022a8d7495c98400b6c',
  'height': 603864,
  'time': 1573797416,
  'block_index': 603864},
 {'hash': '00000000000000000010c72d7961acfa031b08ad28e76a588f03a4c2fb869895',
  'height': 603863,
  'time': 1573797255,
  'block_index': 603863},
 {'hash': '00000000000000000008c2cec1e6848ff7c389d3b69b1588171c77b542495fda',
  'height': 603862,
  'time': 1573795752,
  'block_index': 603862},
 {'hash': '0000000000000000001195ac5ab4ebe058d2a442486d11b8a11197f8e92d0a95',
  'height': 603861,
  'time': 1573795340,
  'block_index': 603861},
 {'hash': '0000000000000000000295f0ff8f8002f31e215ca0c50f7a896ff516dfd80681',
  'height': 603860,
  'time': 1573795168,
  'block_index': 603860},
 {'hash': '000000000000000000039f58434d880945e95cb79ed8eb21f360d737eaac59f0',
  'height': 603859,
  'time': 1573794243,
  'block_index': 603859},
 {'hash': '00000000000000000010f67ee1d021df2b1c05897fa870a769e2d329fc015a80',
  'height': 603858,
  'time': 1573793708,
  'block_index': 603858},
 {'hash': '000000000000000000052d2dde30bb9a6aae6729c24686a63ebb91dd8860bc80',
  'height': 603857,
  'time': 1573793694,
  'block_index': 603857},
 {'hash': '0000000000000000000317498e78f1b4dc0758db4bea32198e208a21d70afcba',
  'height': 603856,
  'time': 1573792985,
  'block_index': 603856},
 {'hash': '00000000000000000011c8d7a713d6271b412bb9a5d1188bd1904e0777e42389',
  'height': 603855,
  'time': 1573792724,
  'block_index': 603855},
 {'hash': '000000000000000000008789ded69a65bcb1645bbea1b6d91d8a619699f2848b',
  'height': 603854,
  'time': 1573791657,
  'block_index': 603854},
 {'hash': '000000000000000000045bccfe8e3ed5a8505371542a193a2f5e65e2501b9599',
  'height': 603853,
  'time': 1573790594,
  'block_index': 603853},
 {'hash': '0000000000000000000e21339087b1a2be089dcca7cf0feb7e19d7545ee3a71c',
  'height': 603852,
  'time': 1573790501,
  'block_index': 603852},
 {'hash': '00000000000000000012e0934c1766ea1bc1e7db9cf3924083fee9dbc4fb12d6',
  'height': 603851,
  'time': 1573790111,
  'block_index': 603851},
 {'hash': '0000000000000000000f3557fe03236d58cc9b2c3ab871e1192ce89565492179',
  'height': 603850,
  'time': 1573790062,
  'block_index': 603850},
 {'hash': '000000000000000000150a704736da0c7e252ec610a0bb3a6e335de72f0dbf58',
  'height': 603849,
  'time': 1573789234,
  'block_index': 603849},
 {'hash': '00000000000000000014554619aec4e3c8ddaa02a6f5aacdbf729a534e1b38f5',
  'height': 603848,
  'time': 1573789061,
  'block_index': 603848},
 {'hash': '0000000000000000001535f4a2fad913fee2674a4cee3e48ad6497181b16dc59',
  'height': 603847,
  'time': 1573788850,
  'block_index': 603847},
 {'hash': '0000000000000000000a361cedc56b98e75b82ceddba35842dee79259cbd042e',
  'height': 603846,
  'time': 1573788450,
  'block_index': 603846},
 {'hash': '00000000000000000004c628df479d89312765b487b5dfaeebc1c45ea43227e5',
  'height': 603845,
  'time': 1573788280,
  'block_index': 603845},
 {'hash': '00000000000000000015c85e107ea85ef61bba6d6374a7b527190f6d2d036962',
  'height': 603844,
  'time': 1573788144,
  'block_index': 603844},
 {'hash': '0000000000000000000b226fbb9cbaeff5511a00296828a791265f37fdaadb42',
  'height': 603843,
  'time': 1573788135,
  'block_index': 603843},
 {'hash': '0000000000000000000349c23428fad07bee1224374282fbab34d2e4be48a884',
  'height': 603842,
  'time': 1573786567,
  'block_index': 603842},
 {'hash': '0000000000000000000ebbc47d24934a3fbeffc8be61534f561d66656bb6489a',
  'height': 603841,
  'time': 1573785722,
  'block_index': 603841},
 {'hash': '000000000000000000017dc1e4cf47192387b6045302327d9036b93e3c2e8eb3',
  'height': 603840,
  'time': 1573785507,
  'block_index': 603840},
 {'hash': '00000000000000000008efef3801d0424256149243a163bc414d6e8b112b226a',
  'height': 603839,
  'time': 1573784560,
  'block_index': 603839},
 {'hash': '00000000000000000007adee53e88ee6dba8bf82cd773587a4bd201a1174565f',
  'height': 603838,
  'time': 1573784508,
  'block_index': 603838},
 {'hash': '0000000000000000000005444f0fe469fa040b8c411cf1aa810902a374861850',
  'height': 603837,
  'time': 1573783110,
  'block_index': 603837},
 {'hash': '000000000000000000113bc02bb22e7cb93eb6ad8b7c5f8709161977495fccf8',
  'height': 603836,
  'time': 1573783080,
  'block_index': 603836},
 {'hash': '0000000000000000000cf32d8f7ba59128ddbad95918da950f85de05760ba031',
  'height': 603835,
  'time': 1573782832,
  'block_index': 603835},
 {'hash': '00000000000000000006c357ea84e4da62d214b46e02599efdefc5e88bfaca76',
  'height': 603834,
  'time': 1573782815,
  'block_index': 603834},
 {'hash': '0000000000000000000725c3a2368e462cdade9b70f1d19a4e86e01d9c22f930',
  'height': 603833,
  'time': 1573782309,
  'block_index': 603833},
 {'hash': '00000000000000000005808700303c981731f87adfe8ec16bb44849b9c1897d8',
  'height': 603832,
  'time': 1573782149,
  'block_index': 603832},
 {'hash': '000000000000000000041d61bfd8228b9a84eb35a2f86c5a051afa984aba7e61',
  'height': 603831,
  'time': 1573782061,
  'block_index': 603831},
 {'hash': '0000000000000000000a006aa73dab0e4bb9400a751f0c28e831644dfa69c99d',
  'height': 603830,
  'time': 1573781889,

In [21]:
data = pd.DataFrame(results)
data.head()

,hash,height,time,block_index
0,0000000000000000000efcea1cc1a169955e9cf6f039dd...,603966,1573858343,603966
1,0000000000000000000ee40dc80e8ddd28d6389ba8dd59...,603965,1573857408,603965
2,0000000000000000000cc742f3903cf8960ffd9c51ad17...,603964,1573856957,603964
3,00000000000000000004f941b4a37d7500a1c90a681ed0...,603963,1573856530,603963
4,000000000000000000072200d4179a900d6b4ab78cd0ad...,603962,1573856123,603962